name: gstreamer # you probably want to 'snapcraft register <name>'
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: gstreamer packaged as snap # 79 char long summary
description: |
  GStreamer is a library for constructing graphs of media-handling components. The applications it supports range from simple Ogg/Vorbis playback, audio/video streaming to complex audio (mixing) and video (non-linear editing) processing.(https://gstreamer.freedesktop.org/)


confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable # must be 'stable' to release into candidate/stable channels

parts:
 gstreamer:
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.8.3.tar.xz
    source-checksum: sha256/66b37762d4fdcd63bce5a2bec57e055f92420e95037361609900278c0db7c53f
    # source: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.12.5.tar.xz
    # source-checksum: sha256/9f750d845a326880b24c1ccc913d07df8f38cd9e63009714795ae175b6c29c6a
    configflags:
      - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - liborc-0.4-dev
      - libpulse-dev
      - libxv-dev
      - libtag1-dev
      - libwavpack-dev
      - libusb-1.0-0-dev
    stage-packages:
      - liborc-0.4-dev ## For gst-plugins-base
      - libasound2-dev
      - libjpeg-dev
      - libvpx-dev
      - libvorbis-dev
      - libogg-dev
      - libpulse0
      - libwavpack-dev
      - libvisual-0.4-dev
      - libtag1v5
      - libopus-dev
      - libcairo-gobject2
      - libgdk-pixbuf2.0-dev
      - libpangocairo-1.0-0
      - libtheora-dev
      - libxv-dev
      - libxdamage-dev
      - libcdparanoia-dev
      - libc6-dev ## For gst-plugins-ugly
      - libusb-1.0-0
      - libwayland-egl1-mesa
      - libcurl3
      - libdrm2
      - libx11-xcb1
      - libqt5quick5
      - libwebp5
      - libopenexr22
      - libopencv-calib3d2.4v5
      - libopencv-highgui2.4v5
      - libopencv-objdetect2.4v5
      - libopencv-video2.4v5
      - libqt5x11extras5
      - libdc1394-22
      - libhybris
      - libx264-dev
      - libvdpau-dev
    prime:
      - lib
      - usr/bin
      - usr/include
      - usr/lib
      # - usr/libexec/gstreamer-1.0/gst-completion-helper
      - usr/libexec/gstreamer-1.0/gst-plugin-scanner
      - usr/sbin
      - usr/share
    build-attributes: [no-system-libraries]

 gst-plugins-base:
    after:
      - gstreamer
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.8.3.tar.xz
    source-checksum: sha256/114871d4d63606b4af424a8433cd923e4ff66896b244bb7ac97b9da47f71e79e
    # source: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.12.5.tar.xz
    # source-checksum: sha256/8fd9f25b65f3286f43530868b501a4e7cdc3f1568be78c75da716cd2559b712e
    configflags:
      - --prefix=/usr
    build-packages:
      - gettext
      - liborc-0.4-dev
      - libfribidi-dev
      - libpulse-dev
    prime:
      - lib
      - usr
    stage-packages:
      - libpulse0

    build-attributes: [no-system-libraries]

 gst-plugins-libav:
    after:
      - gstreamer
      - gst-plugins-base
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.8.3.tar.xz
    source-checksum: sha256/9006a05990089f7155ee0e848042f6bb24e52ab1d0a59ff8d1b5d7e33001a495
    # source: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.12.5.tar.xz
    # source-checksum: sha256/812b865f3936d0c5b30f766a126783c99fe00c166c1a7677d50790201c573878
    configflags:
      - --prefix=/usr
      - --enable-gpl
      - --enable-orc
    build-packages:
      - bison
      - flex
      - gettext
      - libgnutls28-dev
      - liborc-0.4-dev
      - libpulse-dev
      - libva-dev
      - libwayland-dev
      - libxrandr-dev
      - yasm
      - zlib1g-dev
    stage-packages:
      - libpulse0
      - libva-wayland1
      - libva-x11-1
      - libva1
      - zlib1g
    prime:
      - lib
      - usr
    build-attributes: [no-system-libraries]

 gst-plugins-good:
    after:
      - gstreamer
      - gst-plugins-base
      - gst-plugins-libav
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.8.3.tar.xz
    source-checksum: sha256/a1d6579ba203a7734927c24b90bf6590d846c5a5fcec01a48201018c8ad2827a
    # source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.12.5.tar.xz
    # source-checksum: sha256/2c84b23bbe06e40c99dece5ea4520b337a15aa4e7eba1290e6d14834e2005555
    configflags:
     - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - liborc-0.4-dev
      - libpulse-dev
    stage-packages:
      - libpulse0
    prime:
      - lib
      - usr
    build-attributes: [no-system-libraries]

 gst-plugins-bad:
    after:
      - gstreamer
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-libav
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.8.3.tar.xz
    source-checksum: sha256/7899fcb18e6a1af2888b19c90213af018a57d741c6e72ec56b133bc73ec8509b
    # source: http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.12.5.tar.xz
    # source-checksum: sha256/40f82fa775ce8ecfc930fd13073e8643b90cba9b6f8dd2462ec45a93120c7d81
    configflags:
     - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libneon27-gnutls-dev
      - liborc-0.4-dev
      - libpulse-dev
      - nettle-dev
    stage-packages:
      - libneon27-gnutls
      - libpulse0
    prime:
      - lib
      - usr
    build-attributes: [no-system-libraries]

 gst-plugins-ugly:
    after:
      - gstreamer
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-libav
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.8.3.tar.xz
    source-checksum: sha256/6fa2599fdd072d31fbaf50c34af406e2be944a010b1f4eab67a5fe32a0310693
    # source: http://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.12.5.tar.xz
    # source-checksum: sha256/67724b0188439b0abd2191ce4cd40ed88e4278cbb784898e16f3ec94760ef96e
    configflags:
     - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - liborc-0.4-dev
    prime:
      - usr
    build-attributes: [no-system-libraries]



apps:
  gst-launch:
    environment:
      # GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-launch-1.0

  gst-inspect:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-inspect-1.0

  gst-typefind:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-typefind-1.0

  gst-discoverer:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-discoverer-1.0

  gst-play:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-play-1.0

  echopath:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: echo $GST_PLUGIN_PATH

  uvch264src:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-launch-1.0 uvch264src 

  v4l2src:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-launch-1.0 v4l2src 

  videotestsrc:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-launch-1.0 videotestsrc

  videotestsrc-ball:
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
    command: usr/bin/gst-launch-1.0 videotestsrc pattern=ball ! video/x-raw,width=640,height=480 ! videoconvert ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5600 -v
