name: gstreamer # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: gstreamer packaged as snap # 79 char long summary
description: |
  GStreamer is a library for constructing graphs of media-handling components. The applications it supports range from simple Ogg/Vorbis playback, audio/video streaming to complex audio (mixing) and video (non-linear editing) processing.(https://gstreamer.freedesktop.org/)


confinement: devmode # use 'strict' once you have the right plugs and slots
grade: devel # must be 'stable' to release into candidate/stable channels

parts:
  gstreamer:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gstreamer
      build: |
        ./autogen.sh
        ./configure --prefix=/apps/gstreamer/git --enable-gtk-doc
        make
      install: |
        make install
# configflags:
#   - "--prefix=/apps/gstreamer/git"
#   - "--enable-gtk-doc"
      build-packages:
      - on amd64: []
      - on armhf: []

  gst-plugins-base:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-base
      build: |
        ./autogen.sh --prefix=/apps/gst-plugins-base/git --enable-gtk-doc --enable-iso-codes --enable-orc
        make
      install: |
        make install

  gst-plugins-good:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
      build: |
        ./autogen.sh --prefix=/apps/gst-plugins-good/git --enable-gtk-doc --enable-orc
        make
      install: |
        make install

  gst-plugins-ugly:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-ugly
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
      build: |
        ./autogen.sh --prefix=/apps/gst-plugins-ugly/git --enable-gtk-doc --enable-orc
        make
      install: |
        make install

  gst-plugins-bad:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-bad
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
      build: |
        ./autogen.sh --prefix=/apps/gst-plugins-bad/git --enable-gtk-doc --enable-orc --with-cuda-prefix=/usr/local/cuda
        make
      install: |
        make install

  gst-libav:
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-libav
      plugin: autotools
      source: git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
      build: |
        ./autogen.sh --prefix=/apps/gst-libav/git --enable-gtk-doc --enable-orc 
        make
      install: |
        make install

build-packages: # Dependencies
   - autoconf
   - automake
   - autogen
   - libtool-bin
   - build-essential
   - gtk-doc-tools
   - liborc-0.4-0
   - liborc-0.4-dev
   - libvorbis-dev
   - libcdparanoia-dev
   - libcdparanoia0
   - cdparanoia
   - libvisual-0.4-0
   - libvisual-0.4-dev
   - libvisual-0.4-plugins
   - libvisual-projectm
   - vorbis-tools
   - vorbisgain
   - libopus-dev
   - libopus-doc
   - libopus0
   - libopusfile-dev
   - libopusfile0
   - libtheora-bin
   - libtheora-dev
   - libtheora-doc
   - libvpx-dev
   - libvpx-doc
   - libvpx3
   - libqt5gstreamer-1.0-0
   - libgstreamer0.10-dev
   - libgstreamer-plugins-base0.10-dev
   - libflac++-dev
   - libavc1394-dev
   - libraw1394-dev
   - libraw1394-doc
   - libraw1394-tools
   - libtag1-dev
   - libtagc0-dev
   - libwavpack-dev
   - wavpack
   - libfontconfig1-dev
   - libfreetype6-dev
   - libx11-dev
   - libxext-dev
   - libxfixes-dev
   - libxi-dev
   - libxrender-dev
   - libxcb1-dev
   - libx11-xcb-dev
   - libxcb-glx0-dev
   - bison
   - flex
