name: gstreamer # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: gstreamer packaged as snap # 79 char long summary
description: |
  GStreamer is a library for constructing graphs of media-handling components. The applications it supports range from simple Ogg/Vorbis playback, audio/video streaming to complex audio (mixing) and video (non-linear editing) processing.(https://gstreamer.freedesktop.org/)


confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable # must be 'stable' to release into candidate/stable channels

parts:
 gstreamer:
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.5.2.tar.xz
    source-checksum: sha256/9f750d845a326880b24c1ccc913d07df8f38cd9e63009714795ae175b6c29c6a
    configflags:
      - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - liborc-0.4-dev
      - libpulse-dev
      - libxv-dev
    prime:
      - usr/bin/gst*
      - usr/lib/gstreamer-1.0/libgst*
      - usr/lib/libgst*
      - usr/libexec/gstreamer-1.0/gst-plugin-scanner
      - usr/share/locale/*
    build-attributes: [no-system-libraries]


 gst-plugins-base:
    after:
      - gstreamer
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.5.2.tar.xz
    source-checksum: sha256/8fd9f25b65f3286f43530868b501a4e7cdc3f1568be78c75da716cd2559b712e
    configflags:
      - --prefix=/usr
    build-packages:
      - gettext
      - libfribidi-dev
      - libpulse-dev
    prime:
      - lib/libjson-c*
      - usr/lib/**/libfribidi.so*
      - usr/lib/gstreamer-1.0
      - usr/lib/libgst*
      - usr/share/locale/*
    build-attributes: [no-system-libraries]

 gst-plugins-good:
    after:
      - gstreamer
      - gst-plugins-base
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.5.2.tar.xz
    source-checksum: sha256/2c84b23bbe06e40c99dece5ea4520b337a15aa4e7eba1290e6d14834e2005555
    configflags:
     - --prefix=/usr
    build-packages:
      - bison
      - flex
      - gettext
      - liborc-0.4-dev
      - libpulse-dev
    prime:
      - lib/libjson-c*
      - usr/lib/gstreamer-1.0
      - usr/lib/libgst*
      - usr/share/locale/*
    # stage-packages:
    #   - libpulse0
    build-attributes: [no-system-libraries]

apps:
  gst-launch:
    command: /usr/bin/gst-launch-1.0

  gst-inspect:
    command: /usr/bin/gst-inspect-1.0

  gst-stats:
    command: /usr/bin/gst-stats-1.0

  gst-typefind:
    command: /usr/bin/gst-typefind-1.0

  uvch264src:
    command: gst-launch-1.0 uvch264src initial-bitrate=1000000 average-bitrate=1000000 iframe-period=1000 device=/dev/video0 name=src auto-start=true src.vidsrc ! video/x-h264,width=1920,height=1080,framerate=24/1 ! h264parse ! rtph264pay ! udpsink host=xxx.xxx.xxx.xxx port=5600

  v4l2src:
    command: gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-h264,width=1920,height=1080,framerate=24/1 ! h264parse ! rtph264pay ! udpsink host=xxx.xxx.xxx.xxx port=5000

  test:
    command: gst-launch-1.0 videotestsrc pattern=ball ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5600